name: "master branch push"

on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: "master branch push"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn --frozen-lockfile --non-interactive

      - name: Build
        run: |
          yarn build

      - name: Commit dist files and Push -f
        run: |
          cd dist
          git init
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add -A
          git commit -m 'deploy'
          git push --quiet --force https://${{ secrets.TOKEN }}@github.com/yiliang114/resume.git master:gh-pages
      # - name: Push changes to gh-pages branch
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.TOKEN }}
      #     branch: gh-pages
      #     force: true

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.REMOTE_TARGET }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
